import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f8f5f0',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#6d28d9',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#ffffff',
  },
  menuButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  menuButtonText: {
    fontSize: 20,
    color: '#ffffff',
    fontWeight: '800',
  },
  hero: {
    paddingHorizontal: 24,
    paddingTop: 36,
    paddingBottom: 48,
  },
  heroTitle: {
    fontSize: 34,
    fontWeight: '800',
    color: '#5b21b6',
    lineHeight: 40,
  },
  heroSubtitle: {
    marginTop: 12,
    fontSize: 16,
    color: '#52606d',
    lineHeight: 22,
  },
  heroActions: {
    marginTop: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  primaryButton: {
    backgroundColor: '#7c3aed',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 15,
  },
  secondaryButton: {
    borderWidth: 2,
    borderColor: '#7c3aed',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
  },
  secondaryButtonText: {
    color: '#7c3aed',
    fontWeight: '700',
    fontSize: 15,
  },
  features: {
    paddingHorizontal: 24,
    paddingVertical: 48,
    backgroundColor: '#ffffff',
  },
  sectionTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#5b21b6',
    textAlign: 'center',
    marginBottom: 24,
  },
  featureCard: {
    backgroundColor: '#f1f5f9',
    padding: 20,
    borderRadius: 18,
    marginBottom: 16,
    shadowColor: '#0f172a',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  featureIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#c4b5fd',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  featureIconText: {
    fontSize: 22,
    color: '#1f2933',
  },
  featureTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1f2933',
    marginBottom: 6,
  },
  featureText: {
    fontSize: 14,
    color: '#52606d',
    lineHeight: 20,
  },
  cta: {
    paddingHorizontal: 24,
    paddingVertical: 56,
    alignItems: 'center',
    backgroundColor: '#6d28d9',
  },
  ctaTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 12,
  },
  ctaText: {
    fontSize: 15,
    color: '#ede9fe',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 22,
  },
  ctaButton: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  ctaButtonText: {
    color: '#6d28d9',
    fontWeight: '800',
    fontSize: 15,
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    zIndex: 10,
  },
  drawer: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: 260,
    backgroundColor: '#ffffff',
    paddingTop: 56,
    paddingHorizontal: 20,
    shadowColor: '#0f172a',
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 6, height: 0 },
    elevation: 8,
  },
  drawerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#5b21b6',
    marginBottom: 16,
  },
  drawerItem: {
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  drawerIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ede9fe',
  },
  drawerIconText: {
    color: '#5b21b6',
    fontWeight: '800',
    fontSize: 12,
  },
  drawerItemText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4c1d95',
  },
  drawerFooter: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
});
